services:
  frontend:
    build:
      context: ../streetcode-frontend-RomaPavl
      dockerfile: Dockerfilefront
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
        - .env
    environment:
      - REACT_APP_BACKEND_URL=${{REACT_APP_BACKEND_URL}}
    networks:
      - product

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
    depends_on:
      - db
      - redis
    env_file:
        - .env
    environment:
      - ASPNETCORE_HTTP_PORT=${{ASPNETCORE_HTTP_PORT}}
      - ASPNETCORE_HTTPS_PORT=${{ASPNETCORE_HTTPS_PORT}}
      - ASPNETCORE_URLS=${{ASPNETCORE_URLS}}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${{ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PASSWORD}}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${{ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH}}
    volumes:
      - ./https:/https
    networks:
      - product
 
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: always
    ports:
      - "1433:1433"
    env_file:
        - .env
    environment:
      - MSSQL_SA_PASSWORD=${{MSSQL_SA_PASSWORD}}
      - ACCEPT_EULA=${{ACCEPT_EULA}}
      - DB_NAME=${{DB_NAME}}
      - DB_USER=${{DB_USER}}
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - product

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - product

volumes:
  sqlserver_data:

networks:
  product:
