name: Testing frontend and backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Creating .env file with necessary envs
      run: |
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "MSSQL_SA_PASSWORD=${{ secrets.MSSQL_SA_PASSWORD }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "ACCEPT_EULA=${{ secrets.ACCEPT_EULA }}" >> .env
        echo "MS_SQL_DB_PORT=${{ secrets.MS_SQL_DB_PORT }}" >> .env
        echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" >> .env
        echo "DOCKER_LOGIN=${{ secrets.DOCKER_LOGIN }}" >> .env
        echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
        echo "ASPNETCORE_HTTPS_PORT=${{ secrets.ASPNETCORE_HTTPS_PORT }}" >> .env
        echo "ASPNETCORE_HTTP_PORT=${{ secrets.ASPNETCORE_HTTP_PORT }}" >> .env
        echo "ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PASSWORD=${{ secrets.ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PASSWORD }}" >> .env
        echo "ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH=${{ secrets.ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH }}" >> .env
        echo "ASPNETCORE_URLS=${{ secrets.ASPNETCORE_URLS }}" >> .env
    - name: Save cert
      run: mkdir -p https && echo "${{ secrets.STREETCODE_CERT }}" | base64 --decode > https/streetcode.pfx
    - name: Build 
      run: cd streetcode-backend-RomaPavl && docker compose build --no-cache
    - name: Setup all infrastructure
      run: cd streetcode-backend-RomaPavl && docker compose up & sleep 30
    - name: Wait for 20s
      run: sleep 20
    - name: Check frontend' logs
      run: docker logs streetcode-backend-romapavl-frontend-1
    - name: Check backend' logs
      run: docker logs streetcode-backend-romapavl-backend-1
    - name: Check database tables
      run: docker exec streetcode-backend-romapavl-db-1 /opt/mssql-tools18/bin/sqlcmd -S "db,${{ secrets.MS_SQL_DB_PORT }}" -U "${{ secrets.DB_USER }}" -P "${{ secrets.MSSQL_SA_PASSWORD }}" -C -Q "SELECT name FROM sys.tables"
    - name: Testing frontend
      run: docker exec streetcode-backend-romapavl-frontend-1 curl -vk http://localhost:3000  
    - name: Testing backend
      run: docker exec streetcode-backend-romapavl-frontend-1 curl -vk https://backend:5001/api/streetcode/getAllMainPage
    - name: Login to the DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin
    - name: Push images to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_LOGIN }}/frontend
        docker push ${{ secrets.DOCKER_LOGIN }}/backend
